language: java 

sudo: false

os: osx
osx_image: xcode9.1
before_install:
  - bash .travis-prepare.sh

install: true

script:
  - mvn -B clean install -f pom.xml

deploy:
  # deploy master to staging
  - 
    provider: script
    script: "sh $TRAVIS_BUILD_DIR/.travis-deploy.sh"
    skip_cleanup: true
    on:
      tags: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.binaries
